const DATABASE_USER = process.env.DATABASE_USER;
const DATABASE_PASSWORD = process.env.DATABASE_PASSWORD;
const DATABASE_URI = process.env.DATABASE_URI;
const SECRET_KEY_TOKEN = process.env.SECRET_KEY_TOKEN;

module.exports = {
  DATABASE_USER,
  DATABASE_PASSWORD,
  DATABASE_URI,
  SECRET_KEY_TOKEN
};
